---
title: "590 HW1"
author: "Austin Turvy Derek Holste Mason Carhart"
date: "4/13/2021"
output: pdf_document
---



```{r}

library(pacman)

<<<<<<< HEAD
p_load(readr, data.table, dplyr, janitor, haven, here, tidyverse, skimr)
=======
p_load(readr, data.table, dplyr, janitor, haven, here)
>>>>>>> 5461940e7d0d92a4a53d1609ed435671267359c7

```



```{r}

af = read_dta(here("afghanistan_anonymized_data.dta")) #%>% clean_names()

```


gen nonoutlier = 1 
replace nonoutlier = 0 if f07_num_ppl_hh_cnt > 20 & f07_observed == 1
replace nonoutlier = 0 if f07_jeribs_cnt > 10 & f07_observed == 1
replace nonoutlier = 0 if f07_num_sheep_cnt > 50 & f07_observed == 1
replace nonoutlier = 0 if s08_num_ppl_hh_cnt > 20 & s08_observed == 1
replace nonoutlier = 0 if s08_jeribs_cnt > 10 & s08_observed == 1
replace nonoutlier = 0 if s08_num_sheep_cnt > 50 & s08_observed == 1



```{r}
af$nonoutlier = 1

af = af %>% mutate(af$nonoutlier, if_else(f07_num_ppl_hh_cnt > 20, if_else(f07_jeribs_cnt > 10 , if_else(f07_observed == 1 ,    if_else(s08_num_ppl_hh_cnt > 20, if_else(s08_jeribs_cnt > 10, if_else(s08_num_sheep_cnt > 50, if_else(f07_observed == 1 , if_else(s08_observed == 1 , 1, 0), 0), 0), 0), 0), 0), 0), 0))

sum(af$nonutlier)

```

```{r}




```

```{r, Derek try}
af$nonoutlier_1 = 1

af <- af %>% mutate(outlier= ifelse((f07_num_ppl_hh_cnt > 20 & f07_observed == 1) |
                                    (f07_jeribs_cnt > 10 & f07_observed == 1)|
                                    (f07_num_sheep_cnt > 50 & f07_observed == 1)|
                                      (s08_num_ppl_hh_cnt > 20 & s08_observed == 1)|
                                      (s08_jeribs_cnt > 10 & s08_observed == 1) |
                                      (s08_num_sheep_cnt > 50 & s08_observed == 1)
                                      ,0,1))


af <- af %>% mutate(o_1 = ifelse(f07_num_ppl_hh_cnt > 20 & f07_observed == 1,0,1))
af <- af %>% mutate(o_2 = ifelse(f07_jeribs_cnt > 10 & f07_observed == 1,0,1))
af <- af %>% mutate(o_3 = ifelse(f07_num_sheep_cnt > 50 & f07_observed == 1,0,1))
af <- af %>% mutate(o_4 = ifelse(s08_num_ppl_hh_cnt > 20 & s08_observed == 1,0,1))
af <- af %>% mutate(o_5 = ifelse(s08_jeribs_cnt > 10 & s08_observed == 1,0,1))
af <- af %>% mutate(o_6 = ifelse(s08_num_sheep_cnt > 50 & s08_observed == 1,0,1))


```


```{r Results, echo=FALSE, results = 'asis'}


reg2 = lm(burden ~ mod + fed_funds_rate + fed_funds_rate*mod, data = blog)

se_burden  <- sqrt(diag(vcovHC(reg2, type = "HC1")))

stargazer(reg2, keep.stat = c('n', 'rsq'),title = "Regression Results",
          se = list(se_burden),
          covariate.labels = c('Before Time Period', "Fed Funds Rate", "After Time Period"),
          dep.var.labels = c('Mortgage Burden'), type = 'latex', header = FALSE, float = TRUE,  notes = "Heteroskedasticity Robust Standard Errors Used for S.E")

#Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```


```{r}

reg1 = lm(  , data = af)


```












